export const mechanicGlossary = {
  amplify: "Increases by +10% for each buff on self",
  combustion:
    "Consumes all Ignite stacks on target, gains +20% ATK per stack consumed",
  concentrate: "Damage increases by 50/20/10/0% for 1/2/3/4 enemies present",
  stuns: "Prevents target from acting for the listed duration.",
  stun: "Prevents the target from acting for the listed duration.",
  ignite: "Each stack increases damage taken by 10%",
  decay: " Decay deals 10% of inflicted skill damage as a DoT",
  pierce: "Ignores enemy defense by a set percentage",
  taunt: "Direct all single target enemy attacks to self",
  taunts: "Direct all single target enemy attacks to self",
  cleanse: "Removes debuffs from the ally target(s).",
  cleanses: "Removes debuffs from the ally target(s).",
  spite: "Increases damage by +2% for each 1% missing HP",
  weakpoint: "Deals 3x damage against debuffed enemies",
  shock: "DoT equal to 30% of the damage dealt; each application stacks independently; cleansable",
  bleed: "DoT equal to 90% of the damage dealt; each application stacks independently; cleansable",
  detonate: "Damage increases by 20% for each point of the target's ultimate gauge",
  critical: "Ignores 50% defense and type advantage/disadvantage, deals +50% damage",
  charged: "Each stack raises ATK, DEF and evade chance by 5%",
  evade: "Chance to fully avoid an attack — no damage, no effects. Base evade is 0%",
  rupture: "Deals 2x damage against buffed enemies",
  lifesteal: "Recovers HP equal to a percentage of the damage dealt",
  extort: "Lowers enemy ATK/DEF and adds the stolen points to own stats for the duration; never stacks",
  extorts: "Lowers enemy ATK/DEF and adds the stolen points to own stats for the duration; never stacks",
  seals: "Blocks the listed skill type for the duration; ultimates are unaffected",
  deathblow: "Damage and crit chance +2% for every 3% of max HP lost",
  crit: "A critical hit: ignores 50% defense and type matchups, +50% damage",
  countered: "A unit in a counter stance strikes back when attacked (unless the hit kills it)",
  lowers: "Reduces the target's stat by 20%",
  "greatly lowers": "Reduces the target's stat by 50%",
  "massively lowers": "Reduces the target's stat by 80%",
} as const;

export type MechanicKeyword = keyof typeof mechanicGlossary;
